#!/usr/bin/env python3
"""DKCash, the loan management program using a GnuCash database.

Once the program is finished, this should start a GUI as well.
"""

import argparse
from datetime import date

from dkcashlib import dkhandle, dkdata
from dkcashlib.common import (Creditor, Contract)


def _parse_arguments():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('-f', '--file', type=str, default="dkcash.sqlite",
                        help="The GnuCash database file")
    parser.add_argument('-b', '--base_dk', type=str, default=None,
                        help="The base account for `Direktkredite`.")
    parser.add_argument('-a', '--base_ausgleich', type=str, default=None,
                        help="The base account for the balancing account.")
    parser.add_argument('-z', '--base_zinsen', type=str, default=None,
                        help="The base account for the interest account.")

    return parser.parse_args()


def main():
    """The main function of this script."""
    args = _parse_arguments()
    # print("args:")
    # print(args)
    # data = dkdata.DKData(gnucash_file=args.file,
    #                      base_dk=args.base_dk,
    #                      base_ausgleich=args.base_ausgleich,
    #                      base_zinsen=args.base_zinsen)
    connection = dkhandle.Connection(gnucash_file=args.file)
    creditor = Creditor(
        "Someone", ["address line 1", "address line 2"],
        phone="+491234567890", email="hallo@example.com",
        connection=connection)
    contract = Contract(
        "2038", creditor.creditor_id, date="2001-01-01", amount=1234.56,
        interest=0.1, period_end=date(2000, 1, 1), connection=connection)
    # creditor.delete()

    retrieved = Contract.retrieve(connection=connection,
                                  contract_id="2038")

    import IPython; IPython.embed()


if __name__ == "__main__":
    main()
